### ISSUE TITLE
Obsidian自定义样式修改教程 - 知乎

### ISSUE THREAD

**Issue by was1840** [was1840/webClipper#1]
## Obsidian 自定义样式修改教程

最后编辑时间：2021 年 5 月 20 日 16:53:08

我边学习 CSS 边写这个教程。

有什么没讲到的地方欢迎在评论区留言，根据大家的提问会进一步完善本教程。

* * *

## 基本概念介绍

-   什么是 markdown
-   什么是 HTML
-   什么是 CSS

### 什么是 markdown

Markdown 是一种可以使用普通文本编辑器编写的标记语言，通过简单的标记语法，它可以使普通文本内容具有一定的格式。obsidian 使用的是扩展的 markdown 格式。

### 什么是 HTML

超文本标记语言 (HyperText Markup Language,HTML) 是构成 Web 世界的一砖一瓦。它定义了网页内容的含义和结构。我们熟悉的网页都是由 HTML 构成的。以下列举了几种 markdown 转换为 HTML 的对应格式：

```html
<h1>一级标题</h1>
<h2>二级标题</h1>
<h3>三级标题</h1>
<h4>四级标题</h1>
<h5>五级标题</h1>
<h6>六级标题</h1>
<p>段落</p>
<ol>
    <li>有序列表</li>
    <li>有序列表</li>
    <li>有序列表</li>
</ol>
<ul>
    <li>无序列表</li>
    <li>无序列表</li>
    <li>无序列表</li>
</ul>
<a href="">链接</a>
<img src="" alt="图片">
<blockquote>引用</blockquote>
<code>代码块</code>
<hr>分割线
```

### 什么是 CSS

层叠样式表（Cascading Style Sheet，CSS）是用于控制网页样式的标记性语言。在 obsidian 中，markdown 被解析成 HTML，因此需要使用 CSS 修改其显示样式。 CSS 类似于 Microsoft Office Word 中的 “样式” 功能。  
obsidian 的 CSS 存放位置在笔记库文件夹下`.obsidian`的`themes`和`snippets`这两个文件夹。`thems`主要放置主题 CSS 文件，而`snippets`主要放置 CSS 片段。

![](https://pic1.zhimg.com/v2-b0bf702285a8f9a48576874c03453434_b.jpg)
![](https://pic1.zhimg.com/v2-069d53ff1e543456e56473fc820f886c_b.jpg)

CSS 基本使用方法

-   基础语法
-   变量
-   编辑软件准备

### 基础语法

CSS 是定义 HTML 中特定元素样式的一组规则，比如 “我希望页面中的一级标题的红色的字”，对应的 CSS 代码如下：

语法由一个 `选择器 (selector)`起头。 它 "选择" 了我们将要用来添加样式的 HTML 元素。 在这个例子中我们为一级标题（主标题`<h1>`）添加样式。  
接着输入一对大括号 { }。 在大括号内部定义一个或多个形式为 `属性 (property): 值 (value);` 的 声明。每个声明都指定了我们所选择元素的一个属性，之后跟一个我们想赋给这个属性的值。冒号之前是属性，冒号之后是值。不同的 CSS 属性对应不同的合法值。

![](https://pic3.zhimg.com/v2-fc0c2d3313f12b489c90174610a5429e_b.jpg)

CSS 选择器有如下几个常见的类型： - 标签选择器 - 类选择器 - id 选择器 - 分组选择器 - 后代选择器 - 父子选择器 - 兄弟选择器 - 属性选择器 - 根据状态确定样式

### 标签选择器

通过 HTML 标签进行选择，比如`<p> <h1> <a>`等标签。

```html
<p>这是标签选择器</p>
p {
        color: #f40;
        font-size: 25px;
    }
```

### 类选择器

通过标签的 class 类进行选择，比如`<div class='CodeMirror'> 或者 < div class='markdown-preview-view'>`等类。

```html
<div class='markdown-preview-view'>这是类选择器</div>
.markdown-preview-view {
        color: #f40;
        font-size: 25px;
    }
```

### id 选择器

通过标签的 id 进行选择，比如`<div id='text'>`等 id。obsidian 中貌似用不到 id 选择器（？待确认）

```html
<div class='text'>这是id选择器</div>
#text {
        color: #f40;
        font-size: 25px;
    }
```

### 分组选择器

选择器可以一次选择多种元素设置相同的样式，少写了很多代码。不同选择器使用`,`逗号分隔。

```html
<p>这是分组选择器</p>
<a href="#">world</a>
    <div>
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
        </ul>
    </div>
p,a,li {
        color: blue;
    }
```

### 后代选择器

又称为包含选择器，选择某个标签的所有后代以设置样式，比如 div 内的 ul 内的 li 元素，每一层选择器之间使用空格分隔

```html
<div>
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
        </ul>
    </div>
div ul li {
        color: red;
        list-style: none;
    }
```

### 父子选择器

类似于后代选择器，但是有点不同。如果您不希望选择任意的后代元素，而是希望缩小范围，只选择某个元素的子元素，请使用父子元素选择器。

```html
<div class="class1">
    <p>something被选中了</p>
    <div class="class2">
        <p>something不会被选中</p>
    </div>
</div>
.class1>p {
  color: red;
  text-align: center;
}
```

### 兄弟选择器

也叫关联选择器，用来选择紧挨着的元素的选择器，比如希望选择 h1 元素下面第一个段落 p，而不选择第二个段落 p 以后的元素。

```html
<h1>一级标题</h1>
<p>p1第一段</p>
<p>p2第二段</p>
<p>p3第三段</p>
h1+p {
  color: red;
  font-size: 200%;
}
```

### 属性选择器

通过属性（如 name 属性）进行选择以设置相同的样式

```html
<p name="pra1">这是属性选择器</p>
    <p name="pra2">hello world</p>
[name="pra1"]{
        color: blue;
    }
    [name="pra2"]{
        color: red;
    }
```

### 根据状态确定样式

对于链接可根据它的不同状态分别设置不同的样式，如是否是未访问的、访问过的、被鼠标悬停的等状态。

```html
<a>This is a link</a>
a:link {
    color: pink;
}
a:visited {
    color: green;
}
a:hover {
    text-decoration: none;
}
```

### 变量

对于重复使用的属性值，可以将其设置成变量，便于统一修改，不必一遍又一遍地复制和粘贴相同的属性值。此外，采用合理的变量名，能让其他人一眼就能识别该属性值的作用。如`--background-color-primary`和`--background-color-secondary`

```css
:root {
--background-color-primary: #fbf1c7;
--background-color-secondary: #d5c4a1;
}
.markdown-preview-section
{
    background-color: var(--background-color-primary);
}
```

### 编辑软件准备

本地编辑 CSS 代码的软件推荐使用[vscode](https://link.zhihu.com/?target=https%3A//code.visualstudio.com/)  
为了方便调试，按`Ctrl+Shift+i`打开 chrome 调试工具如下图所示

![](https://pic3.zhimg.com/v2-fbc010458ecf4911280bb1aff35767b2_b.jpg)

点击该按钮后，鼠标移动到你想修改的对象上就可以查看该元素的 CSS 属性值，不仅可以看到正在生效的属性，还可以看到被覆盖掉的属性值。 使用 vscode 编辑 css 代码，保存后自动生效，记得在 obsidian 设置 “外观” 中选择你所编辑的主题。

## 各种元素选择详解

下面开始实战讲解。由于目前 obsidian 还未做到所见即所得，窗口分为编辑模式与预览模式，因此 CSS 样式也要分别为这个两个不同的模型写代码。编辑模式对应`.CodeMirror`类，以及缩写的`.cm-xxx`等类。预览模式对应`.markdown-preview-section`。下面针对两种模式分别进行讲解。

### 编辑模式

标题`.cm-header-x`代表第 x 级标题。

```css
.cm-header-1 {
  font-size: 2em;
}
.cm-header-2 {
  font-size: 1.6em;
}
.cm-header-3 {
  font-size: 1.37em;
}
.cm-header-4 {
  font-size: 1.25em;
}
.cm-header-5,
.cm-header-6 {
  font-size: 1.12em;
}
```

引用文本`cm-quote`

```css
.cm-quote {
    color: red;
}
```

列表`HyperMD-list-line`，其中第 x 级标题为`cm-list-x`

```css
.cm-list-1 {
    color: red;
}
```

具体分别指定有序列表和无序列表使用`.cm-formatting-list-ul`和`.cm-formatting-list-ol`

```css
.cm-formatting-list-ul + span {
    color: red;
}
.cm-formatting-list-ol + span {
    color: blue;
}
```

链接`cm-link`

```css
.cm-s-obsidian span.cm-link, .cm-s-obsidian span.cm-hmd-internal-link {
    color: red;
}
```

斜体`cm-em`加粗`cm-strong`

```css
.cm-em, .cm-strong {
    color: red;
}
```

### 预览模式

标题`.markdown-preview-view hx`代表第 x 级标题。

```css
.markdown-preview-section h1 {
    color: blue !important;
}
```

引用文本`.markdown-preview-view blockquote`

```css
.markdown-preview-view blockquote {
    color: red;
}
```

列表`HyperMD-list-line`，其中第 x 级标题为`cm-list-x`

```css
.cm-list-1 {
    color: red;
}
```

具体分别指定有序列表和无序列表使用`ul`和`ol`

```css
ul {
    color: red;
}
ol {
    color: blue;
}
```

链接`cm-link`

```css
a:link {
    color: red;
}
a:hover {
    color: blue;
}
a:visited {
    color: green;
}
```

斜体`em`加粗`strong`

## 各种自定义样式详解

-   字体
-   字号
-   颜色
-   背景颜色
-   缩进
-   行距
-   页面宽度

### 字体

字体分为本地字体和网络字体。**注意：一般字体都需要收费，自己个人免费用没事，一旦涉及商业用途需要收费。**  将网络上的字体下载并安装后，直接使用字体的名字即可，可同时设置多个字体，系统从最左边开始使用，找不到该字体会顺延至下一个字体。

```css
body{
    font-family: '宋体','黑体';
}
```

也可以根据网址引用网络字体

```css
@font-face {
    font-family: 'Hanalei Fill';
    font-style: normal;
    font-weight: 400;
    src: url(https://fonts.gstatic.font.im/s/hanaleifill/v11/fC1mPYtObGbfyQznIaQzPQi8UAjF.ttf) format('truetype');
  }
body{
    font-family: 'Hanalei Fill';
}
```

### 字号

字号有很多种单位：px 像素，pt 磅和 em 相对字体大小

```css
.cm-header-1 {
  font-size: 2em;
}
.cm-header-2 {
  font-size: 18px;
}
.cm-header-3 {
  font-size: 20pt;
}
```

### 颜色

找到你想修改的那部分元素，修改它的 color 属性值。

```css
.markdown-preview-section {
    color: blue ;
}
```

### 背景颜色

背景颜色同理，

```css
.markdown-preview-view {
    background-color: blue;
}
```

或者修改 color 相关的变量

```css
.theme-dark {
    --background-primary: #566352;
    --background-primary-alt: #1a1a1a;
    --background-secondary: #161616;
    --background-secondary-alt: #000000;
    --background-modifier-border: #333;
    --background-modifier-form-field: rgba(0, 0, 0, 0.3);
    --background-modifier-form-field-highlighted: rgba(0, 0, 0, 0.22);
    --background-modifier-box-shadow: rgba(0, 0, 0, 0.3);
    --background-modifier-success: #197300;
    --background-modifier-error: #3d0000;
    --background-modifier-error-rgb: 61, 0, 0;
    --background-modifier-error-hover: #470000;
    --background-modifier-cover: rgba(0, 0, 0, 0.8);
}
```

### 首行缩进

修改 text-indent 属性即可。 编辑模式

```css
pre.CodeMirror-line:not(.HyperMD-header){
    text-indent: 2em;
}
```

预览模式

```css
.markdown-preview-section p{
    text-indent: 2em;
}
```

### 行距

修改 line-height 属性即可

```css
pre.CodeMirror-line:not(.HyperMD-header){
    line-height: 2em;
}
```

### 页面宽度

分别修改编辑模式和预览模式的 max-width 属性。obsidian 默认是 700px

```css
.markdown-source-view.is-readable-line-width .CodeMirror {
    max-width: 1000px;
}
.markdown-preview-view.is-readable-line-width .markdown-preview-sizer{
    max-width: 1000px;
}
```

### 文章被以下专栏收录

\[

![](https://pic1.zhimg.com/4b70deef7_xs.jpg?source=172ae18b)

](//www.zhihu.com/column/c_1302994040707948544)

\[

obsidian 软件技巧

## ](//www.zhihu.com/column/c_1302994040707948544)

分享 obsidian 软件的使用技巧，请查看置顶

### 推荐阅读

\[

# 2017 最新最完整 web 前端学习流程

第一章 初级课程 第 1 天 html 1、HTTP 协议 2、html 是纯文本 3、html 骨架 4、DTD 文档类型 5、head 标签 6、body 标签 7、html 基本语法 8、h 系列的标签 9、p 标签 10、img 标签 11、a 标签 12、div…

Lin12580

]([https://zhuanlan.zhihu.com/p/30430229](https://zhuanlan.zhihu.com/p/30430229))\[

![](https://pic1.zhimg.com/e1591e2e45f61841d55e970d208318f1_250x0.jpg?source=172ae18b)

# 自定义邮件主题行正文预览

王雪皎发表于邮件营销叮...

]([https://zhuanlan.zhihu.com/p/19697192](https://zhuanlan.zhihu.com/p/19697192))\[

# obsidian 插件 dataview 官方文档翻译

一、说明 对官方文档进行翻译工作 网站标题：dataview 官方文档 网站地址：[https://blacksmithgu.github.io/obsidian-dataview/docs/intro](https://blacksmithgu.github.io/obsidian-dataview/docs/intro) 网站说明：入门介绍 Dataview 是一个在你的知识库中…

宏沉一笑

]([https://zhuanlan.zhihu.com/p/393550306](https://zhuanlan.zhihu.com/p/393550306))\[

# 网页制作的相关练习

1\. 静态网页使用（B）语言来制作。 A：c B:HTML C:JAVA D:VBscripr 2.html 称为：（D） A: 可扩展标识语言 B：可扩展超文本标识语言 C：标识语言 D：超文本标识语言 3. 下列软件用来网页图形图…

放山栏人

]([https://zhuanlan.zhihu.com/p/23395464](https://zhuanlan.zhihu.com/p/23395464))

## 12 条评论

​切换为时间排序

写下你的评论...

发布

-   [![](https://pic2.zhimg.com/da8e974dc_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/mang-guo-da-di)

    [芒果大帝](//www.zhihu.com/people/mang-guo-da-di)​08-23

    请问按 Ctrl+Shift+i 打开 chrome 调试工具后，调整了参数颜色，如何保存设置呢？重启 OB 后自定义的参数又消失了。

    ​1​回复​踩​ 举报
-   ![](https://pic3.zhimg.com/da8e974dc_s.jpg?source=06d4cd63)
    知乎用户 (作者) 回复[芒果大帝](//www.zhihu.com/people/mang-guo-da-di)​08-23

    调试模式是保存不了的，必须写到 css 文件里

    ​赞​回复​踩​ 举报

-   [![](https://pic2.zhimg.com/v2-e80f2afce283498bbce980c7b9e6af64_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/lu-ren-66-10)

    [路人](//www.zhihu.com/people/lu-ren-66-10)09-01

    我就想改个超链接的颜色，到了 N 多地方都找不到。  
    Ctrl+Shift+i，直接解决了，谢谢大哥！

    ​赞​回复​踩​ 举报

-   [![](https://pic2.zhimg.com/v2-eeff1b41454efb207c15c79cb04b73a6_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/chi-shang-9-93)

    [蓝月休宁](//www.zhihu.com/people/chi-shang-9-93)08-29

    请问标签，tag, 怎么设置？

    ​赞​回复​踩​ 举报

-   [![](https://pic3.zhimg.com/v2-121773abebff3564c40c12adf473feea_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/ren-ren-xiao-54)

    [任仁笑](//www.zhihu.com/people/ren-ren-xiao-54)​08-26

    想问问按 Ctrl+shift+i 调试模式，透明背景消失变成实体背景怎么办嘞？还有如何能所见即所得地调呢？（调试模式调后重新打开没了，但用其他软件调无法所见即所得）

    ​赞​回复​踩​ 举报

-   [![](https://pic3.zhimg.com/v2-217736f05ac524de2f2e85db82150609_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/fanrasy)

    [CrazyEl](//www.zhihu.com/people/fanrasy)07-29

    感谢解答![](https://pic2.zhimg.com/v2-3e36d546a9454c8964fbc218f0db1ff8.png)

    ​赞​回复​踩​ 举报

-   [![](https://pica.zhimg.com/v2-e9594c9b3de43eca5dfc6ce65744bfcd_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/lu-tian-bei-99)

    [路天北](//www.zhihu.com/people/lu-tian-bei-99)07-24

    小白想问一下 css 文件怎么做 直接用笔记本改后缀行吗 还是必须要用 vs？

    ​赞​回复​踩​ 举报
-   ![](https://pic1.zhimg.com/da8e974dc_s.jpg?source=06d4cd63)
    知乎用户 (作者) 回复[路天北](//www.zhihu.com/people/lu-tian-bei-99)07-24

    记事本写也可以. notepad++, vscode 这类代码编辑器写起来更方便，而且程序也不大

    ​赞​回复​踩​ 举报
-   [![](https://pic3.zhimg.com/v2-e9594c9b3de43eca5dfc6ce65744bfcd_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/lu-tian-bei-99)

    [路天北](//www.zhihu.com/people/lu-tian-bei-99)回复知乎用户 (作者) 07-24

    但是我把别人提供的代码复制到记事本里，然后改后缀，放在我 snippets 位置，并没有出现预期的效果 不知道是哪里出了问题

    ​赞​回复​踩​ 举报

展开其他 1 条回复

-   [![](https://pic3.zhimg.com/v2-318cc37ac004f5683a58c4606376980b_s.jpg?source=06d4cd63)
    ](//www.zhihu.com/people/shi-yan-chao-60)

    [SGC 飘舞](//www.zhihu.com/people/shi-yan-chao-60)05-27

    我想问一下，段落首行缩进的 CSS 加在哪个部位？

    ​赞​回复​踩​ 举报
-   ![](https://pic1.zhimg.com/da8e974dc_s.jpg?source=06d4cd63)
        知乎用户 (作者) 回复[SGC 飘舞](//www.zhihu.com/people/shi-yan-chao-60)05-28
        obsidian的CSS存放位置在笔记库文件夹下.obsidian的themes和snippets这两个文件夹。添加在你使用的主题css文件最后几行，或者你新建一个css文件放在snippets文件夹里（记得在ob设置里打开snippets）

        ​2​回复​踩​ 举报
    Obsidian 自定义样式修改教程

* * *

最后编辑时间：2021 年 5 月 20 日 16:53:08

我边学习 CSS 边写这个教程。

有什么没讲到的地方欢迎在评论区留言，根据大家的提问会进一步完善本教程。

* * *

## 基本概念介绍

-   什么是 markdown
-   什么是 HTML
-   什么是 CSS

### 什么是 markdown

Markdown 是一种可以使用普通文本编辑器编写的标记语言，通过简单的标记语法，它可以使普通文本内容具有一定的格式。obsidian 使用的是扩展的 markdown 格式。

### 什么是 HTML

超文本标记语言 (HyperText Markup Language,HTML) 是构成 Web 世界的一砖一瓦。它定义了网页内容的含义和结构。我们熟悉的网页都是由 HTML 构成的。以下列举了几种 markdown 转换为 HTML 的对应格式：

```html
<h1>一级标题</h1>
<h2>二级标题</h1>
<h3>三级标题</h1>
<h4>四级标题</h1>
<h5>五级标题</h1>
<h6>六级标题</h1>
<p>段落</p>
<ol>
    <li>有序列表</li>
    <li>有序列表</li>
    <li>有序列表</li>
</ol>
<ul>
    <li>无序列表</li>
    <li>无序列表</li>
    <li>无序列表</li>
</ul>
<a href="">链接</a>
<img src="" alt="图片">
<blockquote>引用</blockquote>
<code>代码块</code>
<hr>分割线
```

### 什么是 CSS

层叠样式表（Cascading Style Sheet，CSS）是用于控制网页样式的标记性语言。在 obsidian 中，markdown 被解析成 HTML，因此需要使用 CSS 修改其显示样式。 CSS 类似于 Microsoft Office Word 中的 “样式” 功能。  
obsidian 的 CSS 存放位置在笔记库文件夹下`.obsidian`的`themes`和`snippets`这两个文件夹。`thems`主要放置主题 CSS 文件，而`snippets`主要放置 CSS 片段。

![](https://pic1.zhimg.com/80/v2-b0bf702285a8f9a48576874c03453434_720w.jpg)
![](https://pic1.zhimg.com/80/v2-069d53ff1e543456e56473fc820f886c_720w.jpg)

CSS 基本使用方法

-   基础语法
-   变量
-   编辑软件准备

### 基础语法

CSS 是定义 HTML 中特定元素样式的一组规则，比如 “我希望页面中的一级标题的红色的字”，对应的 CSS 代码如下：

```css
h1 {
    color: red;
}
```

语法由一个 `选择器 (selector)`起头。 它 "选择" 了我们将要用来添加样式的 HTML 元素。 在这个例子中我们为一级标题（主标题`<h1>`）添加样式。  
接着输入一对大括号 { }。 在大括号内部定义一个或多个形式为 `属性 (property): 值 (value);` 的 声明。每个声明都指定了我们所选择元素的一个属性，之后跟一个我们想赋给这个属性的值。冒号之前是属性，冒号之后是值。不同的 CSS 属性对应不同的合法值。

![](https://pic3.zhimg.com/80/v2-fc0c2d3313f12b489c90174610a5429e_720w.jpg)

CSS 选择器有如下几个常见的类型： - 标签选择器 - 类选择器 - id 选择器 - 分组选择器 - 后代选择器 - 父子选择器 - 兄弟选择器 - 属性选择器 - 根据状态确定样式

### 标签选择器

通过 HTML 标签进行选择，比如`<p> <h1> <a>`等标签。

```html
<p>这是标签选择器</p>
p {
        color: #f40;
        font-size: 25px;
    }
```

### 类选择器

通过标签的 class 类进行选择，比如`<div class='CodeMirror'> 或者 < div class='markdown-preview-view'>`等类。

```html
<div class='markdown-preview-view'>这是类选择器</div>
.markdown-preview-view {
        color: #f40;
        font-size: 25px;
    }
```

### id 选择器

通过标签的 id 进行选择，比如`<div id='text'>`等 id。obsidian 中貌似用不到 id 选择器（？待确认）

```html
<div class='text'>这是id选择器</div>
#text {
        color: #f40;
        font-size: 25px;
    }
```

### 分组选择器

选择器可以一次选择多种元素设置相同的样式，少写了很多代码。不同选择器使用`,`逗号分隔。

```html
<p>这是分组选择器</p>
<a href="#">world</a>
    <div>
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
        </ul>
    </div>
p,a,li {
        color: blue;
    }
```

### 后代选择器

又称为包含选择器，选择某个标签的所有后代以设置样式，比如 div 内的 ul 内的 li 元素，每一层选择器之间使用空格分隔

```html
<div>
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
        </ul>
    </div>
div ul li {
        color: red;
        list-style: none;
    }
```

### 父子选择器

类似于后代选择器，但是有点不同。如果您不希望选择任意的后代元素，而是希望缩小范围，只选择某个元素的子元素，请使用父子元素选择器。

```html
<div class="class1">
    <p>something被选中了</p>
    <div class="class2">
        <p>something不会被选中</p>
    </div>
</div>
.class1>p {
  color: red;
  text-align: center;
}
```

### 兄弟选择器

也叫关联选择器，用来选择紧挨着的元素的选择器，比如希望选择 h1 元素下面第一个段落 p，而不选择第二个段落 p 以后的元素。

```html
<h1>一级标题</h1>
<p>p1第一段</p>
<p>p2第二段</p>
<p>p3第三段</p>
h1+p {
  color: red;
  font-size: 200%;
}
```

### 属性选择器

通过属性（如 name 属性）进行选择以设置相同的样式

```html
<p name="pra1">这是属性选择器</p>
    <p name="pra2">hello world</p>
[name="pra1"]{
        color: blue;
    }
    [name="pra2"]{
        color: red;
    }
```

### 根据状态确定样式

对于链接可根据它的不同状态分别设置不同的样式，如是否是未访问的、访问过的、被鼠标悬停的等状态。

```html
<a>This is a link</a>
a:link {
    color: pink;
}
a:visited {
    color: green;
}
a:hover {
    text-decoration: none;
}
```

### 变量

对于重复使用的属性值，可以将其设置成变量，便于统一修改，不必一遍又一遍地复制和粘贴相同的属性值。此外，采用合理的变量名，能让其他人一眼就能识别该属性值的作用。如`--background-color-primary`和`--background-color-secondary`

```css
:root {
--background-color-primary: #fbf1c7;
--background-color-secondary: #d5c4a1;
}
.markdown-preview-section
{
    background-color: var(--background-color-primary);
}
```

### 编辑软件准备

本地编辑 CSS 代码的软件推荐使用[vscode](https://link.zhihu.com/?target=https%3A//code.visualstudio.com/)  
为了方便调试，按`Ctrl+Shift+i`打开 chrome 调试工具如下图所示

![](https://pic3.zhimg.com/80/v2-fbc010458ecf4911280bb1aff35767b2_720w.jpg)

点击该按钮后，鼠标移动到你想修改的对象上就可以查看该元素的 CSS 属性值，不仅可以看到正在生效的属性，还可以看到被覆盖掉的属性值。 使用 vscode 编辑 css 代码，保存后自动生效，记得在 obsidian 设置 “外观” 中选择你所编辑的主题。

## 各种元素选择详解

下面开始实战讲解。由于目前 obsidian 还未做到所见即所得，窗口分为编辑模式与预览模式，因此 CSS 样式也要分别为这个两个不同的模型写代码。编辑模式对应`.CodeMirror`类，以及缩写的`.cm-xxx`等类。预览模式对应`.markdown-preview-section`。下面针对两种模式分别进行讲解。

### 编辑模式

标题`.cm-header-x`代表第 x 级标题。

```css
.cm-header-1 {
  font-size: 2em;
}
.cm-header-2 {
  font-size: 1.6em;
}
.cm-header-3 {
  font-size: 1.37em;
}
.cm-header-4 {
  font-size: 1.25em;
}
.cm-header-5,
.cm-header-6 {
  font-size: 1.12em;
}
```

引用文本`cm-quote`

```css
.cm-quote {
    color: red;
}
```

列表`HyperMD-list-line`，其中第 x 级标题为`cm-list-x`

```css
.cm-list-1 {
    color: red;
}
```

具体分别指定有序列表和无序列表使用`.cm-formatting-list-ul`和`.cm-formatting-list-ol`

```css
.cm-formatting-list-ul + span {
    color: red;
}
.cm-formatting-list-ol + span {
    color: blue;
}
```

链接`cm-link`

```css
.cm-s-obsidian span.cm-link, .cm-s-obsidian span.cm-hmd-internal-link {
    color: red;
}
```

斜体`cm-em`加粗`cm-strong`

```css
.cm-em, .cm-strong {
    color: red;
}
```

### 预览模式

标题`.markdown-preview-view hx`代表第 x 级标题。

```css
.markdown-preview-section h1 {
    color: blue !important;
}
```

引用文本`.markdown-preview-view blockquote`

```css
.markdown-preview-view blockquote {
    color: red;
}
```

列表`HyperMD-list-line`，其中第 x 级标题为`cm-list-x`

```css
.cm-list-1 {
    color: red;
}
```

具体分别指定有序列表和无序列表使用`ul`和`ol`

```css
ul {
    color: red;
}
ol {
    color: blue;
}
```

链接`cm-link`

```css
a:link {
    color: red;
}
a:hover {
    color: blue;
}
a:visited {
    color: green;
}
```

斜体`em`加粗`strong`

```css
em,strong{
    color: red;
}
```

## 各种自定义样式详解

-   字体
-   字号
-   颜色
-   背景颜色
-   缩进
-   行距
-   页面宽度

### 字体

字体分为本地字体和网络字体。**注意：一般字体都需要收费，自己个人免费用没事，一旦涉及商业用途需要收费。**  将网络上的字体下载并安装后，直接使用字体的名字即可，可同时设置多个字体，系统从最左边开始使用，找不到该字体会顺延至下一个字体。

```css
body{
    font-family: '宋体','黑体';
}
```

也可以根据网址引用网络字体

```css
@font-face {
    font-family: 'Hanalei Fill';
    font-style: normal;
    font-weight: 400;
    src: url(https://fonts.gstatic.font.im/s/hanaleifill/v11/fC1mPYtObGbfyQznIaQzPQi8UAjF.ttf) format('truetype');
  }
body{
    font-family: 'Hanalei Fill';
}
```

### 字号

字号有很多种单位：px 像素，pt 磅和 em 相对字体大小

```css
.cm-header-1 {
  font-size: 2em;
}
.cm-header-2 {
  font-size: 18px;
}
.cm-header-3 {
  font-size: 20pt;
}
```

### 颜色

找到你想修改的那部分元素，修改它的 color 属性值。

```css
.markdown-preview-section {
    color: blue ;
}
```

### 背景颜色

背景颜色同理，

```css
.markdown-preview-view {
    background-color: blue;
}
```

或者修改 color 相关的变量

```css
.theme-dark {
    --background-primary: #566352;
    --background-primary-alt: #1a1a1a;
    --background-secondary: #161616;
    --background-secondary-alt: #000000;
    --background-modifier-border: #333;
    --background-modifier-form-field: rgba(0, 0, 0, 0.3);
    --background-modifier-form-field-highlighted: rgba(0, 0, 0, 0.22);
    --background-modifier-box-shadow: rgba(0, 0, 0, 0.3);
    --background-modifier-success: #197300;
    --background-modifier-error: #3d0000;
    --background-modifier-error-rgb: 61, 0, 0;
    --background-modifier-error-hover: #470000;
    --background-modifier-cover: rgba(0, 0, 0, 0.8);
}
```

### 首行缩进

修改 text-indent 属性即可。 编辑模式

```css
pre.CodeMirror-line:not(.HyperMD-header){
    text-indent: 2em;
}
```

预览模式

```css
.markdown-preview-section p{
    text-indent: 2em;
}
```

### 行距

修改 line-height 属性即可

```css
pre.CodeMirror-line:not(.HyperMD-header){
    line-height: 2em;
}
```

### 页面宽度

分别修改编辑模式和预览模式的 max-width 属性。obsidian 默认是 700px

```css
.markdown-source-view.is-readable-line-width .CodeMirror {
    max-width: 1000px;
}
.markdown-preview-view.is-readable-line-width .markdown-preview-sizer{
    max-width: 1000px;
}
```

 [https://zhuanlan.zhihu.com/p/373888121](https://zhuanlan.zhihu.com/p/373888121)
